# Generated by Django 5.2.9 on 2026-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='appuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
